### ISSUE TITLE
Error rendering report: render command error:file in C:\XXXX\XXXX doesn't have a valid JSON contenttype

### ISSUE THREAD

**Issue by gmedina-GCIB** [jsreport/jsreport-dotnet#5] opened 2017-10-10 16:54 UTC
Hey guys I'm encountering this error when trying to generate reports with your jsreport-dotnet development solution.

I'm getting this exact error when the process go through this code block:

```
var reqFile = Path.Combine(_tempPath, $"req{Guid.NewGuid().ToString()}.json");
File.WriteAllText(reqFile, requestString);

var outFile = Path.Combine(_tempPath, $"out{Guid.NewGuid().ToString()}");
var metaFile = Path.Combine(_tempPath, $"meta{Guid.NewGuid().ToString()}");
var output = await _binaryProcess.ExecuteExe($"render --keepAlive --request={reqFile} --out={outFile} --meta={metaFile}").ConfigureAwait(false);

```

The output result is:

`output.Command = C:\Users\XXXX\AppData\Local\Temp\.jsreport\binary-default-1.8.2.0\jsreport.exerender --keepAlive --request=C:\Users\XXXX\AppData\Local\Temp\jsreport-temp\req00d4a350-4a94-4f2d-af76-fae057bbce50.json --out=C:\Users\XXXX\AppData\Local\Temp\jsreport-temp\out9030077f-aa55-42ef-b710-8f04afcee5f0 --meta=C:\Users\XXXX\AppData\Local\Temp\jsreport-temp\meta9f61dd49-9dde-4ea9-bc44-d713924af1ec`

`output.IsError = True`

`output.Logs = 'render command error:file in C:\Users\XXXX doesn't have a valid JSON contenttype jsreport render -h to get help about usage and available options'`

Any help would be really appreciate it, thanks!

**Comment by gmedina-GCIB** [comment] 2017-10-10 17:39
I tried running CoolM1234 sample project on [issue 4](https://github.com/jsreport/jsreport-dotnet/issues/4)

But I'm getting the same error:

![screenshot 1](https://user-images.githubusercontent.com/32681516/31401250-38ae0cc4-ada7-11e7-9c6e-aebf5d2abb9c.png)

**Comment by pofider** [comment] 2017-10-10 18:00
Thank you for the bug report. I'm looking into it. Could you post here the file 
`C:\Users\XXXX\AppData\Local\Temp\jsreport-temp\req00d4a350-4a94-4f2d-af76-fae057bbce50.json` ?

**Comment by gmedina-GCIB** [comment] 2017-10-10 18:03
@pofider thanks for the quick response, sure here it is:

[req00d4a350-4a94-4f2d-af76-fae057bbce50.json.txt](https://github.com/jsreport/jsreport-dotnet/files/1372894/req00d4a350-4a94-4f2d-af76-fae057bbce50.json.txt)

**Comment by pofider** [comment] 2017-10-10 18:06
Thank you. There is nothing wrong with it.

I have a suspicion that the problem is the space in your username and in the path `c:\users\foo foo\.,,`. I've the space in my username as well and it works. However I have a feeling that it is somehow symlinked in my windows 10. Looking into it.

**Comment by pofider** [comment] 2017-10-10 18:17
Ok, I can replicate the issue. Working on a fix.

**Comment by pofider** [comment] 2017-10-10 19:34
Please update [jsreport.Local@1.0.3](https://www.nuget.org/packages/jsreport.Local/1.0.3) and let me know if it works for you afterwards. Thank you.

**Comment by gmedina-GCIB** [comment] 2017-10-10 20:13
@pofider thanks a lot, it's working now.

You may closed this issue, the problem was solved.

**Comment by pofider** [comment] 2017-10-10 20:14
Thank you for confirmation. Closing this now.

**Closed by pofider** 2017-10-10 20:14 UTC
