### ISSUE TITLE
Exception Thrown consistantly when trying simple example in video.

### ISSUE THREAD

**Issue by shawty** [jsreport/jsreport-dotnet#42] opened 2019-12-11 15:51 UTC
Trying to get started with JsReport.NET and can't even get the firt example working.  All I get when running the code is the following exception:

    jsreport.Local.JsReportBinaryException: 'Error rendering report: looking for previously daemonized 
    instance in: C:\Users\shawty\AppData\Local\Temp\jsreport\cli\sock\workerSock cwd: 
    J:\Programming Projects\Test Stuff\JsReportConsole\JsReportConsole\bin\Debug\netcoreapp3.1
    \jsreportA critical error occurred while trying to execute the render command (2). connect 
    ETIMEDOUT 127.0.0.1:5488 (1). caused by error (2):{    at onCriticalError (D:\snapshot\jsreport
    \node_modules\jsreport-cli\lib\commands\render.js:302:19)    at exports.handler (D:\snapshot
    \jsreport\node_modules\jsreport-cli\lib\commands\render.js:198:14)    at process._tickCallback 
    (internal/process/next_tick.js:68:7)caused by error (1):-> meta = 
    {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":5488}-> 
    stackError:    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)'

Here's what I see in visual Studio:
![image](https://user-images.githubusercontent.com/1876454/70636212-0ae35c80-1c2d-11ea-91ed-0c494991db6c.png)

The code I'm testing is exactly the same as is in the intro video on the .NET sdk web page:

    using jsreport.Binary;
    using jsreport.Local;
    using jsreport.Types;
    using System;
    using System.IO;
    using System.Threading.Tasks;
    
    namespace JsReportConsole
    {
      class Program
      {
        static async Task Main(string[] args)
        {
          Console.WriteLine("Hello World!");
    
          var rs = new LocalReporting()
              .UseBinary(JsReportBinary.GetBinary())
              .AsUtility()
              .Create();
    
          var report = await rs.RenderAsync(new RenderRequest
          {
            Template = new Template
    
            {
              Recipe = Recipe.PhantomPdf,
              Engine = Engine.None,
              Content = "<style>h1 { color: red }</style><h1>Hello World</h1>"
            }
          });
    
          using(var fs = File.Create("out.pdf"))
          {
            report.Content.CopyTo(fs);
          }
    
        }
      }
    }
    
I have installed the latest JsReport NuGet packages:

![image](https://user-images.githubusercontent.com/1876454/70636474-7cbba600-1c2d-11ea-9ab2-ac73d6a57df9.png)

and am targeting Dot Net Core 3.1:
![image](https://user-images.githubusercontent.com/1876454/70636530-9a890b00-1c2d-11ea-9a7b-c16cef43fcd1.png)

Which automatically activates the C#8 compiler.

I'm running in Visual Studio 2019 Community Preview

![image](https://user-images.githubusercontent.com/1876454/70636635-cb694000-1c2d-11ea-80f0-a252e61439f9.png)

My app console outputs:
![image](https://user-images.githubusercontent.com/1876454/70636711-e8057800-1c2d-11ea-8396-4d86f448557e.png)

My Node and Npm versions are as follows:
![image](https://user-images.githubusercontent.com/1876454/70636777-01a6bf80-1c2e-11ea-8449-35c6dedc4311.png)

Running on a 24 core Intel Xeon workstation with 20gb of Ram under Windows 10 X64 V1809

**Comment by pofider** [comment] 2019-12-11 16:24
The problem is that you use `Recipe.PhantomPdf` and this recipe isn't part of the jsreport v2. You should use the `Recipe.ChromePdf`.  See the default recipes marked here https://jsreport.net/learn/recipes

I apologize for the meaningless error message. We will check why it is so bad.

Also, I would recommend trying using pre-release binary `jsreport.Binary@2.6.2-beta2`. There are some important fixes.
I am closing this, feel free to comment further if you find other problems.

**Closed by pofider** 2019-12-11 16:24 UTC

**Comment by shawty** [comment] 2019-12-11 16:26
Hi pofider thanks for that.  Can you possibly mention this fact in the video then, as I feel many like me will use that as their first "test" into seeing if the toolkit is of use to them.

It looks like a VERY promising system, and I absolutely want to use it, but this first experience was not a good one :-)

**Comment by pofider** [comment] 2019-12-11 17:33
Yes, I wrote it at least to the video description as youtube doesn't allow me to put a text directly to the existing video.

**Comment by shawty** [comment] 2019-12-11 18:42
I don't know if you are aware, just for reference :-)   It's easy to add subtitles to a video now on YT, and you don't have to edit the video.

You simply provide a text file with lines with a time and the text in EG:

00:30-00:45 - Hello and Welcome to JsReport

And that text will stay on screen over the video for 15 seconds starting at 30 seconds.  The sub titles don't have to match what you say in the video, and when you embed the video in a web page, you can actually set (I think) something like &subtitles=1 or similar on the URL to turn them on automatically.

I know this, because I'm deaf, so I've done a lot of research into how it all works.

Thanks again ...   I have my test app(s) working now, my next test is to test them on a linux install :-)

**Comment by shawty** [comment] 2019-12-12 00:06
Not a problem, but I have one more quick question if I may, I'll open a new issue if you want me too.

When producing the PDF, how do I get the ChromePdf recipe to produce an A4 size document.  Currently everything it produces is the USA "Letter Size" equivalent and I need to produce UK/Europe A4 sized documents.

I've been through the docs here: https://jsreport.net/learn/dotnet-local a few times and can't see anything that tells me otherwise.

**Comment by pofider** [comment] 2019-12-12 13:39
Hm, it should be by default A4.
However you can explicitely set page size [here](https://github.com/jsreport/jsreport-dotnet-types/blob/master/jsreport.Types/Request/Chrome.cs#L17)

and use something like

```
rs.renderAsync(new RenderRequest {
  Template = new Template {
     ....,
    Chrome = new Chrome {
       Format = "A4"
    }
  }

}
```

Btw I would strongly recommend playing the first just with the full jsreport running with node.js. Play with the studio and get the idea of its capabilities. Just afterward switch to the .net because of integration.

**Comment by shawty** [comment] 2019-12-12 14:36
Thanks, yes I have been playing with the studio, but the problem is I have a boss breathing down my neck that wants to see a printed A4 document asap :-)  I'm sure you know the score :-D
